### ISSUE TITLE
[BUG] The NAV package should recommend the smbclient and dhcping packages

### ISSUE THREAD

**Issue by lunkwill42** [Uninett/nav-debian#17]
As one user reported in Uninett/navappliance#2, the `smbclient` and `dhcping` tools are not installed in the navappliance, even though some optional NAV components depend on these.

These should be listed as recommended packages by the NAV packages, since they aren't outright necessary for normal NAV operation, but become necessary if you start to monitor DHCP servers or samba file shares using servicemon.

**Comment by hmpf** [comment]
Fix merged, closing
