### ISSUE TITLE
Error after update to NAV 4.8 version

### ISSUE THREAD

**Issue by jsinic** [Uninett/nav-debian#4]
Hi 

After apply update on server to NAV version 4.8. I have this errorr. 
[ERROR_logs.txt](https://github.com/UNINETT/nav-debian/files/1504954/ERROR_logs.txt)

![image](https://user-images.githubusercontent.com/19690548/33254625-eba40eba-d349-11e7-9ba3-08ec7d9e538c.png)

**Comment by lunkwill42** [comment]
Closing, as it's outdated.
