### ISSUE TITLE
Lots of "cannot handle special file" messages upon purge.

### ISSUE THREAD

**Issue by vegard1985** [Uninett/nav-debian#8]
**Describe the bug**
See appended log.

**To Reproduce**
1. Go to '...' - Install, following instructions on nav.uninett.no
2. Click on '....' - purge. (apt-get purge nav)
3. Scroll down to '....' - ...the bottom of the output
4. See error - indeed you do. Or just see the appended log.

**Expected behavior**
Purge, without a large quantity of exceptions.

**Screenshots**
See logfile.

**Environment (please complete the following information):**
 - If the problem is with the web ui: Your OS, Browser and browser version [e.g. Windows, Chrome 64]
 - OS on the NAV server [e.g. Debian 10] - Linux DebianLaptop 4.9.0-9-686-pae Uninett/nav#1 SMP Debian 4.9.168-1+deb9u3 (2019-06-16) i686 GNU/Linux

 - NAV version installed [e.g. 4.9.8] - the one recommended for Debian 9, on nav.uninett.no as per 04/10-2019
 - Method of installation [e.g. from Debian package] - the one recommended for Debian 9, on nav.uninett.no as per 04/10-2019

**Additional context**
Reading package lists...
Building dependency tree...
Reading state information...
The following packages were automatically installed and are no longer required:
  graphite-carbon icedtea-netx icedtea-netx-common libapache2-mod-wsgi
  libbytes-random-secure-perl libcrypt-passwdmd5-perl
  libcrypt-random-seed-perl libdbi1 libgammu-i18n libgammu8 libgsmsd8
  libmath-random-isaac-perl libmath-random-isaac-xs-perl libodbc1 librrd8
  linux-image-4.9.0-8-686-pae makepasswd nbtscan python-attr
  python-cffi-backend python-click python-colorama python-constantly
  python-cryptography python-enum34 python-gammu python-idna
  python-incremental python-ipaddress python-openssl python-pam python-pyasn1
  python-pyasn1-modules python-serial python-service-identity
  python-twisted-bin python-twisted-core python-whisper python-zope.interface
  rrdtool rsync wwwconfig-common
Use 'sudo apt autoremove' to remove them.
The following packages will be REMOVED:
  nav*
0 upgraded, 0 newly installed, 1 to remove and 0 not upgraded.
1 not fully installed or removed.
After this operation, 279 MB disk space will be freed.
Do you want to continue? [Y/n] (Reading database ... 
(Reading database ... 5%
(Reading database ... 10%
(Reading database ... 15%
(Reading database ... 20%
(Reading database ... 25%
(Reading database ... 30%
(Reading database ... 35%
(Reading database ... 40%
(Reading database ... 45%
(Reading database ... 50%
(Reading database ... 55%
(Reading database ... 60%
(Reading database ... 65%
(Reading database ... 70%
(Reading database ... 75%
(Reading database ... 80%
(Reading database ... 85%
(Reading database ... 90%
(Reading database ... 95%
(Reading database ... 100%
(Reading database ... 303503 files and directories currently installed.)
Removing nav (4.9.8-2) ...
(Reading database ... 
(Reading database ... 5%
(Reading database ... 10%
(Reading database ... 15%
(Reading database ... 20%
(Reading database ... 25%
(Reading database ... 30%
(Reading database ... 35%
(Reading database ... 40%
(Reading database ... 45%
(Reading database ... 50%
(Reading database ... 55%
(Reading database ... 60%
(Reading database ... 65%
(Reading database ... 70%
(Reading database ... 75%
(Reading database ... 80%
(Reading database ... 85%
(Reading database ... 90%
(Reading database ... 95%
(Reading database ... 100%
(Reading database ... 284269 files and directories currently installed.)
Purging configuration files for nav (4.9.8-2) ...
Looking for files to backup/remove ...

*....and then a LOT of lines looking similar to this one... So many, I wasnt allowed to post the whole of it....*

/usr/sbin/deluser: Cannot handle special file /proc/1008/task/1201/fd/25

**Comment by lunkwill42** [comment]
There's really nothing we can do about that. Purging the package runs Debian's `deluser` command to remove the `navcron` user and any files that are owned by it. The `deluser` program prints lots of warnings about files it doesn't know how to handle (even though it had no intention of deleting that file). You should take it up with Debian upstream.
