### ISSUE TITLE
[BUG] Database initialization fails on install

### ISSUE THREAD

**Issue by eisengrau** [Uninett/nav-debian#9]
Hello,

I tried to install NAV on a Debian Buster LXC container. At install, it seems like the database creation script fails:

`Database initialization failed                                                                                                         │
                                                                      │                                                                                                                                        │
                                                                      │ Script output:                                                                                                                         │
                                                                      │                                                                                                                                        │
                                                                      │ createdb: database creation failed: ERROR: new encoding (UTF8) is incompatible with the encoding of the template database (SQL_ASCII)  │
                                                                      │ HINT: Use the same encoding as in the template database, or use template0 as template.                                                 │
                                                                      │ Failed creating database nav                                                                                                           │
                                                                      │ Creating database nav owned by nav`

I have changed the default locale on the system to EN_UK.UTF-8, but when I do an apt-get install nav, I get the same error moving on. I also get the following right after I run install:

`Attempt to modify config file /etc/nav/db.conf failed  │
                                                                                                              │                                                        │
                                                                                                              │ Script output:  `

Script output is blank.

Did I miss a step? It seems like all dependencies are installed, followed the Debian install instructions.

**Comment by lunkwill42** [comment]
Well, actually, in this case, your PostgreSQL database cluster was initialized before your configured your locale. Changing the system locale after-the-fact will not update the existing PostgreSQL cluster encoding - you will need to drop the database cluster and re-create it (assuming you haven't put important data into it already).

Check out the Debian commands `pg_lscluster`, `pg_dropcluster` and `pg_createcluster`.

**Comment by eisengrau** [comment]
Yes, that did the trick. I just re-created the container, and set the locale right before install, and it worked. Thank you!
